export const ADD_DATA_CLASS = 'ADD_DATA_CLASS';
export const REMOVE_DATA_CLASS = 'REMOVE_DATA_CLASS';
export const SET_FIELD_NAME = 'SET_FIELD_NAME';
export const SET_FIELD_TYPE = 'SET_FIELD_TYPE';
export const ADD_INPUT_SET = 'ADD_INPUT_SET';
export const REMOVE_INPUT_SET = 'REMOVE_INPUT_SET';
